### ISSUE TITLE
Interacting with a categorical variable

### ISSUE THREAD

**Issue by jeffwong-nflx** [topepo/recipes#92] opened 2017-09-13 04:55 UTC
In a standard model.matrix call I can interact a variable `V1` with a categorical variable `label` using `Class ~ V1 * label`

Under the hoods, label is expanded into multiple columns using one hot encoding, and those columns will be called `labelB`, `labelC` etc. Throughout the process I do not need to worry about the function changing the name. 

Using recipes, what is the right set up for using step_dummy and step_interact together? If I call for the interaction V1:label in step_interact, I have to process `label` using step_dummy first. By doing so, I have to keep track of the fact that after step_dummy, there is no longer a column named `label`, and therefore I cannot use that name in step_interact.

```r
data("Sonar")
Sonar = cbind(Sonar, label = c(rep("A", 104), rep("B", 104)))

sonar_rec <- recipe(Class ~ ., data = Sonar) %>%
  step_dummy(all_nominal())# %>%
  #step_interact(~ V1:label)
  
prep(sonar_rec, Sonar) %>% bake(Sonar)
```

**Comment by topepo** [comment] 2017-09-14 00:57
To start, I'm not completely content with the interface to specify interactions. 

You can find the current set of available variables using the `summary` method: 
```r
> sonar_rec <- recipe(Class ~ ., data = Sonar) %>%
+   step_dummy(all_nominal()) %>%
+   prep(Sonar)
step 1 dummy training 
> 
> ## See the current variable names after the dummy
> ## variables are created
> summary(sonar_rec) %>% tail
# A tibble: 6 x 4
  variable    type      role   source
     <chr>   <chr>     <chr>    <chr>
1      V57 numeric predictor original
2      V58 numeric predictor original
3      V59 numeric predictor original
4      V60 numeric predictor original
5  label_B numeric predictor  derived
6  Class_R numeric predictor  derived
```
From this, you can setup the interaction specification. 

You _should_ be able to do something like `step_interact(~ starts_with("label_"):label)` (but that won't work right now). I'll work on making this interface better but suggestions are welcome.

**Comment by jeffwong-nflx** [comment] 2017-09-14 06:08
Great, I didn't notice that `starts_with` existed. When that functionality is available I think it will be an OK interface

**Comment by petersonR** [comment] 2017-09-20 22:45
Hello,

I am also having a little trouble figuring out the syntax with this issue. Specifically, I don't know the order in which the user should specify the dummy variables and the interactions. In the code below, I present my first 3 tries at making a simple (reproducible) example work, all of which have issues. The last try is an attempt at doing what you suggested in your last comment, though I still run into an error when running `prep`.

```
data(biomass)

# Create factor variable
biomass$carbon3 <- cut(biomass$carbon, 3, labels = c('Low', 'Med', 'High'))

biomass_tr <- biomass[biomass$dataset == "Training",]
biomass_te <- biomass[biomass$dataset == "Testing",]

rec <- recipe(HHV ~ carbon3 + hydrogen + oxygen + nitrogen + sulfur,
              data = biomass_tr)

# Try1: First do step_dummy, then step_interact (documentation recommendation)
try_1 <- rec %>%
  step_dummy(all_nominal(), -all_outcomes()) %>% 
  step_interact(terms = ~ carbon3:hydrogen)
  
try_1_prep <- prep(try_1, biomass_tr) # Error, carbon3 not found

# Try2: First do step_interact, then step_dummy (yields warning, but close to correct result)
try_2 <- rec %>%
  step_interact(terms = ~ carbon3:hydrogen) %>%
  step_dummy(all_nominal(), -all_outcomes())  

try_2_prep <- prep(try_2, biomass_tr) # Warning...
bake(try_2_prep) # Correct matrix, although in the wrong order

# Try3: doing both separately 
try_3 <- rec %>% 
  step_dummy(all_nominal(), -all_outcomes()) %>% 
  prep(biomass_tr)

# Use try_3 term info to build formula for step_interact
myFormula <- as.formula(
  paste0('~ hydrogen*(',
         paste0(try_3$term_info$variable[6:7], collapse = ' + '),
         ')'
  )
)

try_3 <- try_3 %>%
  step_interact(terms = myFormula)

prep(try_3, biomass_tr) # error, carbon3_Med not found

```

So, the second try yielded the correct results, yet still produced a warning. Is there a better way of doing this that I am not considering? Thanks!

**Comment by jeffwong-nflx** [comment] 2017-10-24 05:04
Pinging this issue again. Thanks

**Comment by topepo** [comment] 2017-11-13 01:03
@petersonR Just getting around to this...

> `try_1_prep <- prep(try_1, biomass_tr) # Error, carbon3 not found`

Once you make dummy variables, the original variable isn't there anymore. 

```r
> # to start:
> rec %>%
+   prep(biomass_tr) %>% 
+   summary
# A tibble: 6 x 4
  variable    type      role   source
     <chr>   <chr>     <chr>    <chr>
1  carbon3 nominal predictor original
2 hydrogen numeric predictor original
3   oxygen numeric predictor original
4 nitrogen numeric predictor original
5   sulfur numeric predictor original
6      HHV numeric   outcome original
> 
> # then make dummy variables
> rec %>%
+   step_dummy(all_nominal(), -all_outcomes()) %>%
+   prep(biomass_tr) %>% 
+   summary
# A tibble: 7 x 4
      variable    type      role   source
         <chr>   <chr>     <chr>    <chr>
1     hydrogen numeric predictor original
2       oxygen numeric predictor original
3     nitrogen numeric predictor original
4       sulfur numeric predictor original
5          HHV numeric   outcome original
6  carbon3_Med numeric predictor  derived
7 carbon3_High numeric predictor  derived
```

> `bake(try_2_prep, newdata = biomass_tr) # Correct matrix, although in the wrong order`

It is brittle (hence the warning). Without letting the recipe know that `carbon3` was converted to dummy variables, it thinks that it is still there:
```r
> rec %>%
+   step_interact(terms = ~ carbon3:hydrogen) %>%
+   prep(biomass_tr) %>% 
+   summary  
# A tibble: 8 x 4
                variable    type      role   source
                   <chr>   <chr>     <chr>    <chr>
1                carbon3 nominal predictor original
2               hydrogen numeric predictor original
3                 oxygen numeric predictor original
4               nitrogen numeric predictor original
5                 sulfur numeric predictor original
6                    HHV numeric   outcome original
7  carbon3Med_x_hydrogen numeric predictor  derived
8 carbon3High_x_hydrogen numeric predictor  derived
```

> `# Try3: doing both separately `

That ***should*** have worked but is a bug. You can do it all at once _if_ you know the right formula. 

```r
> try_5 <- rec %>% 
+   step_dummy(all_nominal(), -all_outcomes()) %>% 
+   step_interact(terms = ~ hydrogen * (carbon3_Med + carbon3_High)) %>%
+   prep(biomass_tr) 
> summary(try_5)
# A tibble: 9 x 4
                 variable    type      role   source
                    <chr>   <chr>     <chr>    <chr>
1                hydrogen numeric predictor original
2                  oxygen numeric predictor original
3                nitrogen numeric predictor original
4                  sulfur numeric predictor original
5                     HHV numeric   outcome original
6             carbon3_Med numeric predictor  derived
7            carbon3_High numeric predictor  derived
8  hydrogen_x_carbon3_Med numeric predictor  derived
9 hydrogen_x_carbon3_High numeric predictor  derived
> bake(try_5, biomass_tr)
# A tibble: 456 x 9
   hydrogen oxygen nitrogen sulfur    HHV carbon3_Med carbon3_High hydrogen_x_carbon3_Med
      <dbl>  <dbl>    <dbl>  <dbl>  <dbl>       <dbl>        <dbl>                  <dbl>
 1     5.64  42.94     0.41   0.00 20.008           1            0                   5.64
 2     5.70  41.30     0.20   0.00 19.228           1            0                   5.70
 3     5.80  46.25     0.11   0.02 18.299           1            0                   5.80
 4     4.97  35.60     3.30   0.16 18.151           1            0                   4.97
 5     5.40  40.72     1.00   0.02 18.450           1            0                   5.40
 6     5.75  40.20     2.04   0.10 18.465           1            0                   5.75
 7     5.99  38.19     2.68   0.20 18.670           1            0                   5.99
 8     5.70  39.70     1.70   0.20 18.271           1            0                   5.70
 9     5.50  40.90     0.80   0.00 18.631           1            0                   5.50
10     5.90  40.00     1.20   0.10 18.851           1            0                   5.90
# ... with 446 more rows, and 1 more variables: hydrogen_x_carbon3_High <dbl>
```

That's not a very good solution though. 

I'll work on the bug but first I should take a swipe at the interface improvement mentioned above since that might obviate the bug.

**Comment by topepo** [comment] 2017-11-14 21:47
I just checked in some code that would allow for selectors to be used in interactions. 

@jeffwong-nflx @petersonR  Can you try it out on you applications and let me know how things go?

**Comment by petersonR** [comment] 2017-11-15 17:36
I like the interface of being able to use selectors in the interaction formula; this is very useful. This seems to work great for most of the cases in my application. In one case, I was hoping to do "all possible two-way interactions", for which there is still a bit of an issue (though a different problem than the original one). Basically, the dummy variables get interacted with each other (which doesn't make sense):

```
rec_dummy <- rec %>% 
  step_dummy(all_nominal(), -all_outcomes()) 

rec_interact <- rec_dummy %>%
  step_interact(terms = ~ all_predictors() * all_predictors()) 

prepped_rec <- prep(rec_interact, biomass_tr)
bake(prepped_rec, biomass_tr)
# A tibble: 456 x 22
   hydrogen oxygen nitrogen sulfur    HHV carbon3_Med carbon3_High hydrogen_x_oxygen hydrogen_x_nitrogen
      <dbl>  <dbl>    <dbl>  <dbl>  <dbl>       <dbl>        <dbl>             <dbl>               <dbl>
 1     5.64  42.94     0.41   0.00 20.008           1            0          242.1816              2.3124
 2     5.70  41.30     0.20   0.00 19.228           1            0          235.4100              1.1400
 3     5.80  46.25     0.11   0.02 18.299           1            0          268.2500              0.6380
 4     4.97  35.60     3.30   0.16 18.151           1            0          176.9320             16.4010
 5     5.40  40.72     1.00   0.02 18.450           1            0          219.8880              5.4000
 6     5.75  40.20     2.04   0.10 18.465           1            0          231.1500             11.7300
 7     5.99  38.19     2.68   0.20 18.670           1            0          228.7581             16.0532
 8     5.70  39.70     1.70   0.20 18.271           1            0          226.2900              9.6900
 9     5.50  40.90     0.80   0.00 18.631           1            0          224.9500              4.4000
10     5.90  40.00     1.20   0.10 18.851           1            0          236.0000              7.0800
# ... with 446 more rows, and 13 more variables: hydrogen_x_sulfur <dbl>, hydrogen_x_carbon3_Med <dbl>,
#   hydrogen_x_carbon3_High <dbl>, oxygen_x_nitrogen <dbl>, oxygen_x_sulfur <dbl>, oxygen_x_carbon3_Med <dbl>,
#   oxygen_x_carbon3_High <dbl>, nitrogen_x_sulfur <dbl>, nitrogen_x_carbon3_Med <dbl>,
#   nitrogen_x_carbon3_High <dbl>, sulfur_x_carbon3_Med <dbl>, sulfur_x_carbon3_High <dbl>,
#   carbon3_Med_x_carbon3_High <dbl>
```

I was able to easily fix this by adding a step_zv at the end which trims the dummy variables that are interacted with each other:

```
rec_dummy <- rec %>% 
  step_dummy(all_nominal(), -all_outcomes()) 

rec_interact <- rec_dummy %>%
  step_interact(terms = ~ all_predictors() * all_predictors()) %>% 
  step_zv(all_predictors())

prepped_rec <- prep(rec_interact, biomass_tr)
bake(prepped_rec, biomass_tr)
# A tibble: 456 x 21
   hydrogen oxygen nitrogen sulfur    HHV carbon3_Med carbon3_High hydrogen_x_oxygen hydrogen_x_nitrogen
      <dbl>  <dbl>    <dbl>  <dbl>  <dbl>       <dbl>        <dbl>             <dbl>               <dbl>
 1     5.64  42.94     0.41   0.00 20.008           1            0          242.1816              2.3124
 2     5.70  41.30     0.20   0.00 19.228           1            0          235.4100              1.1400
 3     5.80  46.25     0.11   0.02 18.299           1            0          268.2500              0.6380
 4     4.97  35.60     3.30   0.16 18.151           1            0          176.9320             16.4010
 5     5.40  40.72     1.00   0.02 18.450           1            0          219.8880              5.4000
 6     5.75  40.20     2.04   0.10 18.465           1            0          231.1500             11.7300
 7     5.99  38.19     2.68   0.20 18.670           1            0          228.7581             16.0532
 8     5.70  39.70     1.70   0.20 18.271           1            0          226.2900              9.6900
 9     5.50  40.90     0.80   0.00 18.631           1            0          224.9500              4.4000
10     5.90  40.00     1.20   0.10 18.851           1            0          236.0000              7.0800
# ... with 446 more rows, and 12 more variables: hydrogen_x_sulfur <dbl>, hydrogen_x_carbon3_Med <dbl>,
#   hydrogen_x_carbon3_High <dbl>, oxygen_x_nitrogen <dbl>, oxygen_x_sulfur <dbl>, oxygen_x_carbon3_Med <dbl>,
#   oxygen_x_carbon3_High <dbl>, nitrogen_x_sulfur <dbl>, nitrogen_x_carbon3_Med <dbl>,
#   nitrogen_x_carbon3_High <dbl>, sulfur_x_carbon3_Med <dbl>, sulfur_x_carbon3_High <dbl>
```

Thanks for clearing up this issue!

**Comment by topepo** [comment] 2017-11-15 18:23
I see the issue. 

I had considered making an additional step that is a shortcut for all two-way interactions. I'll add that for the next release.

**Closed** 2017-11-19 21:52 UTC
Labels: for next release

**Comment by markhwhiteii** [comment] 2020-08-26 01:36
> I had considered making an additional step that is a shortcut for all two-way interactions. I'll add that for the next release.

Did this ever get added @topepo? I've tried using `~ .^2`, but that will include the outcome variables, as well.
